### ISSUE TITLE
Crash on FreeBSD when adding nzbs to queue

### ISSUE THREAD

**Issue by spacecabbie** [nzbget/nzbget#526]
`Sun Apr  1 10:05:04 2018	INFO	nzbget 19.1 daemon-mode
Sun Apr  1 10:05:04 2018	INFO	Executing scheduler-script Completion.py
Sun Apr  1 10:08:04 2018	INFO	Executing scan-script Completion.py for Watchmen (2009) Ultimate Cut 720p BDRip AC3 x264 MacGuffin.nzb
Sun Apr  1 10:08:04 2018	INFO	Adding collection Watchmen (2009) Ultimate Cut 720p BDRip AC3 x264 MacGuffin.nzb to queue
Sun Apr  1 10:08:04 2018	ERROR	Error parsing nzb-file Watchmen (2009) Ultimate Cut 720p BDRip AC3 x264 MacGuffin.nzb: file has no content
Sun Apr  1 10:08:04 2018	ERROR	Could not add collection Watchmen (2009) Ultimate Cut 720p BDRip AC3 x264 MacGuffin.nzb to queue
Sun Apr  1 10:08:04 2018	INFO	Collection Watchmen (2009) Ultimate Cut 720p BDRip AC3 x264 MacGuffin added to history
Sun Apr  1 10:08:49 2018	INFO	nzbget 19.1 daemon-mode
Sun Apr  1 10:08:49 2018	INFO	Executing scheduler-script Completion.py`

~~It happens when i add a download via radarr it just crashes i have to restart and the above is never saved.~~
Correction: any nzb file that gets added.

dumfile:
`ERROR   Error parsing nzb-file 1
INFO    Executing scheduler-script Completion.py
INFO    Completion: Traceback (most recent call last):
INFO    Completion:   File "/mnt/Downloads/scripts/Completion.py", line 1702, in <module>
INFO    Completion:     main()
INFO    Completion:   File "/mnt/Downloads/scripts/Completion.py", line 1676, in main
INFO    Completion:     if 'NZBSP_TASKID' in os.environ: scheduler_call()
INFO    Completion:   File "/mnt/Downloads/scripts/Completion.py", line 1542, in scheduler_call
INFO    Completion:     data = call_nzbget_direct('listgroups')
INFO    Completion:   File "/mnt/Downloads/scripts/Completion.py", line 354, in call_nzbget_direct
INFO    Completion:     response = urllib2.urlopen(request)  # get some data from NZBGet
INFO    Completion:   File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
INFO    Completion:     return opener.open(url, data, timeout)
INFO    Completion:   File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
INFO    Completion:     response = self._open(req, data)
INFO    Completion:   File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
INFO    Completion:     '_open', req)
INFO    Completion:   File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
INFO    Completion:     result = func(*args)
INFO    Completion:   File "/usr/local/lib/python2.7/urllib2.py", line 1228, in http_open
INFO    Completion:     return self.do_open(httplib.HTTPConnection, req)
INFO    Completion:   File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
INFO    Completion:     raise URLError(err)
INFO    Completion: urllib2.URLError: <urlopen error [Errno 61] Connection refused>

 2 threads, 0 KB/s, 0 MB remaining, Avg. 0 KB/s
(Q)uit | (E)dit | (P)ause | (R)ate | (W)indow | (G)roup | (T)ime | n(Z)b                                                                                                                                      I/O warning : failed to load external entity "/mnt/Downloads/1"
                                                              Parsing NZB-document /mnt/Downloads/1 failed
`

**Comment by hugbug** [comment]
What about nzbs added via web interface?

**Comment by spacecabbie** [comment]
same thing crash i must have fucked something up but no clue what i get no errors that direct me on my way :(

**Comment by hugbug** [comment]
I don't like ` I/O warning : failed to load external entity "/mnt/Downloads/1"`.  Something wrong with the path or drive?

**Comment by spacecabbie** [comment]
no everything looks fine i double checked the paths. tested if they could access and write all was ok.

**Comment by spacecabbie** [comment]
small update reverted back to nzbget-19.1_1 and works again its weirt looks like it specific to nzbget-19.1_2 although nu clue why.

**Comment by hugbug** [comment]
There is only version 19.1 of nzbget. 19.1_1 and 19.1_2 are package versions given by package creator/maintainer, someone from synocommunity I suppose.

I guess there was something wrong with path mapping or similar and the issue has been resolved by reinstallation, not related to package version number probably.

**Comment by spacecabbie** [comment]
freebsd pkg i tried going back to that 1_2 still crashed but must be freebsd issue then.

**Comment by hugbug** [comment]
I thought it was on Linux.

Was that "1_2" package previously working for you?
I wonder if you could test the FreeBSD installed offered on NZBGet download page?

**Comment by hugbug** [comment]
Closing this due to lack of feedback.
